on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: windows-test-r3.6.3

jobs:
  windows-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: '3.6.3'

      - name: Install dependencies
        run: |
          install.packages(c("processx", "remotes", "rcmdcheck", "devtools"), type="binary")
          remotes::install_deps(dependencies = TRUE)
          dotR <- file.path(Sys.getenv("HOME"), ".R")
          if (!file.exists(dotR))
            dir.create(dotR)
          M <- file.path(dotR, "Makevars.win")
          if (!file.exists(M))
            file.create(M)
          cat("\nCXX14FLAGS=-O3 -Wno-unused-variable -Wno-unused-function",
              "CXX14 = $(BINPREF)g++ -m$(WIN) -std=c++1y",
              "CXX11FLAGS=-O3 -Wno-unused-variable -Wno-unused-function",
              file = M, sep = "\n", append = TRUE)
        shell: Rscript {0}

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}

      - name: Run example
        run: Rscript ./example/github_actions_test.R


