on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: windows-test

jobs:
  windows-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses:
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: '3.5'

      - name: Install dependencies
        run: |
          install.packages(c("processx", "remotes", "rcmdcheck"), type="binary")
          install.packages("devtools")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}

      - name: Run example
        run: Rscript ./example/github_actions_test.R


