on: [workflow_dispatch]
#  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_github("nmfs-fish-tools/RMAS")
          library(RMAS)
          library(Rcpp)
          d <- system.file(package = "RMAS")
          r4mas <- Module("rmas", dyn.load(paste(d,"/libs/x64/RMAS", .Platform$dynlib.ext, sep = "")))
          input_data <- write_test_data(nyears = 2)
          print(input_data)
        shell: Rscript {0}
